# Generated by Django 2.2.9 on 2020-10-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20180620_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='Customer',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='Customer',
            name='invitations_pending',
            field=models.TextField(blank=True),
        ),
    ]
