# Generated by Django 2.2.9 on 2020-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20201125_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='invitations_pending',
            field=models.TextField(blank=True, help_text='One email per line.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='key',
            field=models.CharField(choices=[('confirm_registration', 'Email asking for confirmation of account.'), ('daily_summary', 'Daily Summary.'), ('forgot_password', 'Forgot Password.'), ('argument_flagging', 'Argument flagging.'), ('invite', 'Invitation to join private account.'), ('non_active_user_warning', 'Non active user warning.')], max_length=64),
        ),
    ]
