# Generated by Django 2.2.9 on 2020-12-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_wording_customer'),
        ('accounts', '0037_auto_20201201_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='available_wordings',
            field=models.ManyToManyField(blank=True, to='core.Wording'),
        ),
    ]
