# Generated by Django 2.2.9 on 2020-12-04 14:10

from django.db import migrations, models
import django.db.models.deletion

def change_notification_wording_from_zero_value_to_null_before_migrate(apps, migration_schema):
    Customer = apps.get_model('accounts', 'Customer')
    for customer in Customer.objects.filter(notification_wording=0):
       customer.notification_wording = None
       customer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20201204_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='notification_wording',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(change_notification_wording_from_zero_value_to_null_before_migrate),
        migrations.AlterField(
            model_name='customer',
            name='notification_wording',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.NotificationWording'),
        ),
    ]
