# Generated by Django 2.2.9 on 2020-12-04 14:20

from django.db import migrations, models
import django.db.models.deletion

def change_default_wording_from_zero_value_to_null_before_migrate(apps, migration_schema):
    Customer = apps.get_model('accounts', 'Customer')
    Wording = apps.get_model('core', 'Wording')
    for customer in Customer.objects.all():
       if customer.default_wording == 0:
           customer.default_wording = None
           customer.save()
       if customer.default_wording:
           wordings = Wording.objects.filter(id=customer.default_wording)
           if len(wordings) == 0:
               customer.default_wording = None
               customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20201204_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='default_wording',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(change_default_wording_from_zero_value_to_null_before_migrate),
        migrations.AlterField(
            model_name='customer',
            name='default_wording',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_customers', to='core.Wording'),
        ),
    ]
