# Generated by Django 2.2.9 on 2020-12-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20201204_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='available_wordings',
            field=models.ManyToManyField(related_name='customers', to='core.Wording'),
        ),
    ]
