# Generated by Django 2.2.9 on 2021-06-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20210121_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='are_private_discussions_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
