# Generated by Django 2.2.9 on 2021-06-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20210604_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auto_update_interval_for_admins',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_update_interval_for_customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='auto_update_interval_for_admins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='auto_update_interval_for_customer',
            field=models.IntegerField(default=0),
        ),
    ]
