# Generated by Django 2.2.24 on 2021-08-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20210604_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='theme',
            field=models.CharField(choices=[('bjv', 'Bjv'), ('brabbl', 'Brabbl'), ('brabbl2021', 'Brabbl2021'), ('eyp', 'Eyp'), ('vorwaerts', 'Vorwaerts'), ('jugendinfo', 'Jugendinfo')], default='brabbl', max_length=24),
        ),
    ]
