# Generated by Django 2.2.24 on 2022-12-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_customeruserinfosettings_show_in_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='undiscussion_ids',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
