# Generated by Django 2.2.24 on 2022-12-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_user_undiscussion_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='undiscussion_ids',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
