# Generated by Django 2.2.9 on 2020-10-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_statement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='description',
            field=models.CharField(null=True, max_length=1024),
        ),
    ]
