# Generated by Django 2.2.9 on 2020-11-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20201118_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedfile',
            name='filename',
            field=models.CharField(max_length=512),
        ),
    ]
