# Generated by Django 2.2.9 on 2020-12-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201120_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='barometer_wording',
            new_name='discussion_wording',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description (optional)'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Webpage URL (optional)'),
        ),
    ]
