# Generated by Django 2.2.9 on 2020-12-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20201201_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wording',
            name='customer',
        ),
    ]
