# Generated by Django 2.2.9 on 2021-01-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_wording_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedfile',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_associated_files', to='core.Statement'),
        ),
    ]
