# Generated by Django 2.2.9 on 2021-01-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_associatedfile_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description (optional)'),
        ),
    ]
