# Generated by Django 2.2.9 on 2021-03-19 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0044_auto_20210319_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='discussion_users',
            field=models.ManyToManyField(related_name='discussion_user_set', through='core.DiscussionUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussionuser',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Discussion'),
        ),
        migrations.AlterField(
            model_name='discussionuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
