# Generated by Django 2.2.9 on 2021-03-19 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210319_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
