# Generated by Django 2.2.9 on 2021-03-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210319_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionuser',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Discussion'),
        ),
    ]
