# Generated by Django 2.2.9 on 2021-06-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20210319_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='original_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='original_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
