# Generated by Django 2.2.24 on 2021-08-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_discussion_barometer_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='barometer_behavior',
            field=models.IntegerField(choices=[(1, 'Barometer always shows the current voting results'), (2, 'Barometer only shows results to users who already voted for this statement'), (3, "Barometer only shows results to users who already voted for this statement, and to users with 'Admin' account")], default=3),
        ),
    ]
