# Generated by Django 2.2.24 on 2021-08-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_discussion_copyright_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='copyright_info',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
