# Generated by Django 2.2.24 on 2022-12-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_statement_copyright_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
