# Generated by Django 2.2.24 on 2022-12-28 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deletion date'),
        ),
        migrations.AddField(
            model_name='news',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
    ]
