# Generated by Django 2.2.24 on 2022-12-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20221228_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='modified_at',
        ),
    ]
