# Generated by Django 2.2.24 on 2022-12-28 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20221228_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='argument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_arguments', to='core.Argument'),
        ),
        migrations.AlterField(
            model_name='news',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_discussions', to='core.Discussion'),
        ),
        migrations.AlterField(
            model_name='news',
            name='statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_statements', to='core.Statement'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
